-- MySQL Script generated by MySQL Workbench
-- jue 04 mar 2021 00:18:32 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`IMAGES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`IMAGES` (
    `ID` BINARY(16) NOT NULL,
    `NAME` VARCHAR(45) NULL,
    `DESCRIPTION` VARCHAR(45) NULL,
    `TOOLTIP` VARCHAR(45) NULL,
    `ORDER` INT NULL,
    PRIMARY KEY (`ID`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GALLERY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`GALLERY` (
    `ID` BINARY(16) NOT NULL,
    `IMAGES_ID` BINARY(16) NOT NULL,
    PRIMARY KEY (`ID`, `IMAGES_ID`),
    INDEX `fk_GALERY_IMAGES1_idx` (`IMAGES_ID` ASC),
    CONSTRAINT `fk_GALERY_IMAGES1`
    FOREIGN KEY (`IMAGES_ID`)
    REFERENCES `mydb`.`IMAGES` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PROJECT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PROJECT` (
    `ID` BINARY(16) NOT NULL,
    `NAME` VARCHAR(45) NULL,
    `LOCATION` VARCHAR(45) NULL,
    `IMAGE` LONGBLOB NULL,
    `EXPLAIN` VARCHAR(45) NULL,
    `STATUS` ENUM('online', 'offline') NULL,
    `GALLERY_ID` BINARY(16) NOT NULL,
    `CREATE_ON` DATETIME NULL,
    `CREATE_BY` VARCHAR(45) NULL,
    `UPDATE_ON` DATETIME NULL,
    `UPDATE_BY` VARCHAR(45) NULL,
    PRIMARY KEY (`ID`, `GALLERY_ID`),
    INDEX `fk_PROJECT_GALERY_idx` (`GALLERY_ID` ASC),
    CONSTRAINT `fk_PROJECT_GALERY`
    FOREIGN KEY (`GALLERY_ID`)
    REFERENCES `mydb`.`GALLERY` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
